server:
  port: 8080
spring:
  application:
    name: clazz-manager
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/clazzManager?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false
    username: root
    password: '!@#$qwerroot123'
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    initial-size: 10
    min-idle: 8
    max-idle: 8
    max-active: 20
    minEvictableIdleTimeMillis: 300000
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: false
    maxPoolPreparedStatementPerConnectionSize: 20
    filters:  stat,wall,log4j2
    connectionPropertie:  druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
  jpa:
    show-sql: true
    database: mysql
  redis:
    host: 127.0.0.1
    port: 6379
    password: 59233
    timeout: 10s
    lettuce:
      pool:
        min-idle: 0
        max-idle: 8
        max-active: 8
        max-wait: -1ms
  session:
    timeout: 14400
mybatis:
  type-aliases-package: com.school.manager.entity
  mapper-locations: classpath:mapper/*.xml
logging:
  level:
    root: info
    com.school.manager: debug
  file: logs/${spring.application.name}.log
system:
  file:
    filePath: /usr/local/project/app/clm/files
jwt:
  config:
    key: ronin
    ttl: 4